spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: services-order
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: mongodb://root:123456789@localhost:27017
      database: db_notify

otel:
  traces:
    exporter: otlp #otlp, zipkin, console, none
  metrics:
    exporter: none #otlp, prometheus, none
  logs:
    exporter: none #otlp, console, none
  exporter:
    otlp:
      traces:
        protocol: grpc
        endpoint: http://localhost:4317
        #headers: api-key=key,config-key=value,code-app=excahnge-order
      metrics:
        protocol: http/protobuf
        endpoint: http://localhost:4318/v1/metrics
      logs:
        protocol: grpc
        endpoint: http://localhost:4317