spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/inventory
    username: root
    password: 123456789

otel:
  traces:
    exporter: otlp #otlp, zipkin, console, none
  metrics:
    exporter: none #otlp, prometheus, none
  logs:
    exporter: none #otlp, console, none
  exporter:
    otlp:
      traces:
        protocol: grpc
        endpoint: http://localhost:4317
        #headers: api-key=key,config-key=value,code-app=excahnge-order
      metrics:
        protocol: http/protobuf
        endpoint: http://localhost:4318/v1/metrics
      logs:
        protocol: grpc
        endpoint: http://localhost:4317