version: '3.8'

services:
  app:
    build: .
    container_name: security-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SecurityApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - network-said

  db:
    image: postgres:15
    container_name: security-db
    environment:
      POSTGRES_DB: SecurityApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - network-said

networks:
  network-said:
    driver: bridge
