#TO RUN ALL THE MICROSERVICES WITH KAFKA USING DOCKER COMPOSE, please use the following commands:

#docker compose down
#docker compose up -d --build

services:

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-kraft-v1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - microservices-net

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.1
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8181:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9101
    networks:
      - microservices-net

  ms-business-products:
    build: ./ms-business-products
    image: ms-business-products:1.0
    container_name: ms-business-products
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: development
    networks:
      - microservices-net

  ms-business-clients:
    build: ./ms-business-clients
    image: ms-business-clients:1.0
    container_name: ms-business-clients
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: development
    networks:
      - microservices-net

  ms-business-address:
    build: ./ms-business-address
    image: ms-business-address:1.0
    container_name: ms-business-address
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: development
    networks:
      - microservices-net

  ms-business-stores:
    build: ./ms-business-stores
    image: ms-business-stores:1.0
    container_name: ms-business-stores
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - microservices-net

  ms-business-orders:
    build: ./ms-business-orders
    image: ms-business-orders:1.0
    container_name: ms-business-orders
    ports:
      - "8084:8084"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: development
      MS_CLIENTS_BASE_URL: http://ms-business-clients:8082
      MS_PRODUCTS_BASE_URL: http://ms-business-products:8081
    depends_on:
      - kafka
      - ms-business-products
      - ms-business-clients
      - ms-business-address
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
