global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'services-order'
    metrics_path: 'services-order/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'services-inventory'
    metrics_path: 'services-inventory/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080']
  - job_name: 'services-notify'
    metrics_path: 'services-notify/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]

      ### Remmplazamos los 3 por:
      #  - job_name: 'otel-collector'
      #    scrape_interval: 2s
      #    static_configs:
      #      - targets: [ 'host.docker.internal:8889' ]
      #- targets: [ 'host.docker.internal:8888' ]