apiVersion: v1
kind: Secret
metadata:
  name: services-secrets
type: Opaque
data:
  url-micro-inventory: aHR0cDovL3NlcnZpY2VzLWludmVudG9yeS1zZXJ2aWNlczo4MDgwL3NlcnZpY2VzLWludmVudG9yeQ==
  # http://services-inventory-services:8080/services-inventory
  # Si estamos en diferentes NS: http://{services}.{namespaces}:{port}
  # Si estamos en el mismo NS: http://{services}:{port}