#Services Database PostgresSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    version: v1
spec:
  selector:
    app: postgres
    version: v1
  ports:
    - name: tcp-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

---
# Services Order Deployment
apiVersion: v1
kind: Service
metadata:
  name: services-order-service
  labels:
    app: services-order
    version: v1
spec:
  selector:
    app: services-order
    version: v1
  ports:
    - name: tcp-services-order
      protocol: TCP
      port: 8081
      targetPort: 8081